services:
  - type: web
    name: itunes-search-redux
    runtime: node
    plan: free
    rootDir: itunes-search-redux
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    healthCheckPath: /api/health
